"""
src/utils/metrics.py — Prometheus textfile metrics for NFT Firewall V12.

Writes to /var/lib/nft-firewall/metrics.prom in Prometheus textfile format,
compatible with node_exporter --collector.textfile.directory.

Zero network exposure — no HTTP server. The watchdog calls metrics_update()
passively on each health-check iteration.

Public API
----------
    from utils.metrics import metrics_update
    metrics_update(iface="wg0")
"""

import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

_METRICS_FILE = Path("/var/lib/nft-firewall/metrics.prom")


def _count_blocked_ips() -> int:
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
        from core.state import set_list, SET_BLOCKED
        return len(set_list(SET_BLOCKED))
    except Exception:
        return 0


def _count_drop_packets() -> int:
    try:
        from utils.analytics import total_drop_packets
        return total_drop_packets()
    except Exception:
        return 0


def _get_handshake_age(iface: str) -> float:
    try:
        result = subprocess.run(
            ["wg", "show", iface, "latest-handshakes"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        for line in result.stdout.splitlines():
            parts = line.strip().split("\t")
            if len(parts) >= 2:
                timestamp = float(parts[1])
                if timestamp > 0:
                    return time.time() - timestamp
        return -1.0
    except Exception:
        return -1.0


def _get_vpn_up(iface: str, handshake_timeout: int = 180) -> int:
    age = _get_handshake_age(iface)
    return 1 if 0 <= age < handshake_timeout else 0


def _count_threatfeed_entries() -> int:
    try:
        from integrations.threatfeed import get_entry_count
        return get_entry_count()
    except Exception:
        return 0


def _count_geo_cidrs() -> int:
    try:
        from integrations.geoblock import get_total_cidr_count
        return get_total_cidr_count()
    except Exception:
        return 0


def metrics_update(iface: str = "wg0") -> None:
    try:
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

        lines = [
            f"# Generated by nft-firewall at {now_str}",
            "",
            "# HELP nft_blocked_ips_total Number of IPs in the blocked_ips nftables set",
            "# TYPE nft_blocked_ips_total gauge",
            f"nft_blocked_ips_total {_count_blocked_ips()}",
            "",
            "# HELP nft_drop_packets_total Cumulative packets denied by nftables drop rules",
            "# TYPE nft_drop_packets_total counter",
            f"nft_drop_packets_total {_count_drop_packets()}",
            "",
            "# HELP nft_vpn_handshake_age_seconds Seconds since last WireGuard handshake",
            "# TYPE nft_vpn_handshake_age_seconds gauge",
            f"nft_vpn_handshake_age_seconds {_get_handshake_age(iface):.1f}",
            "",
            "# HELP nft_vpn_up 1 if VPN is healthy (handshake within threshold), 0 otherwise",
            "# TYPE nft_vpn_up gauge",
            f"nft_vpn_up {_get_vpn_up(iface)}",
            "",
            "# HELP nft_threatfeed_entries_total IPs currently loaded from threat feed",
            "# TYPE nft_threatfeed_entries_total gauge",
            f"nft_threatfeed_entries_total {_count_threatfeed_entries()}",
            "",
            "# HELP nft_geo_blocked_cidrs_total CIDRs currently blocked by geo-blocking",
            "# TYPE nft_geo_blocked_cidrs_total gauge",
            f"nft_geo_blocked_cidrs_total {_count_geo_cidrs()}",
            "",
        ]
        content = "\n".join(lines) + "\n"

        _METRICS_FILE.parent.mkdir(parents=True, exist_ok=True)
        tmp = _METRICS_FILE.with_suffix(".tmp")
        with tmp.open("w") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, _METRICS_FILE)
    except Exception:
        return
