"""
src/core/state.py — nftables state management: apply, backup, restore, set modifiers.

This module owns every side-effectful operation on the live firewall.
It never generates ruleset strings (that is ``core.rules``'s job) and
never sends notifications (that is the CLI / watchdog's job).

Usage
-----
Apply a ruleset generated by ``core.rules``::

    from core.rules import RulesetConfig, generate_ruleset
    from core import state

    cfg     = RulesetConfig(phy_if="eth0", ...)
    ruleset = generate_ruleset(cfg)

    # Validate syntax without touching live rules
    ok, err = state.simulate_apply(ruleset)
    if not ok:
        raise SystemExit(f"Ruleset syntax error: {err}")

    # Backup current state, then apply
    backup_path = state.backup_ruleset()
    try:
        state.apply_ruleset(ruleset)
        state.save_conf(ruleset)
    except RuntimeError:
        state.restore_ruleset(backup_path)
        raise

    # Runtime set manipulation (no re-apply needed)
    state.block_ip("1.2.3.4")
    state.allow_ip("5.6.7.8")
"""

import re
import json
import os
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple

# ── Paths & constants ─────────────────────────────────────────────────────────

_PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent.parent
_BACKUP_DIR:   Path = _PROJECT_ROOT / "state"

NFT_CONF:    Path = Path("/etc/nftables.conf")
SET_BLOCKED:   str  = "blocked_ips"
SET_TRUSTED:   str  = "trusted_ips"
SET_WHITELIST: str  = "geowhitelist_ips"
SET_DK:        str  = "dk_ips"
TABLE:         str  = "ip firewall"

_SETS_STATE_FILE: Path = Path("/var/lib/nft-firewall/dynamic-sets.json")
_AUDIT_LOG_FILE: Path = Path("/var/log/nft-firewall/audit.jsonl")
_KNOWN_SETS: tuple[str, ...] = (SET_BLOCKED, SET_TRUSTED, SET_WHITELIST, SET_DK)


# ── Apply & validate ──────────────────────────────────────────────────────────

def simulate_apply(ruleset: str, nft_cmd: Optional[List[str]] = None) -> Tuple[bool, str]:
    """Validate a ruleset string with ``nft -c -f`` without touching live rules.

    Writes *ruleset* to a temporary file, runs ``nft --check --file`` (or the
    provided compatible command prefix), then deletes the file regardless of
    outcome.

    Parameters
    ----------
    ruleset:
        The nftables ruleset string to validate.
    nft_cmd:
        Optional command prefix compatible with nft's arguments.  For example,
        ``["sudo", "/usr/local/lib/nft-firewall/fw-nft"]``.

    Returns
    -------
    tuple[bool, str]
        ``(True, "")`` if the syntax is valid, or ``(False, error_message)``
        if ``nft`` reported an error.  This function never raises.
    """
    tmp: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", delete=False, prefix="nft_check_"
        ) as fh:
            fh.write(ruleset)
            tmp = Path(fh.name)

        cmd = list(nft_cmd or ["nft"])
        result = subprocess.run(
            cmd + ["--check", "--file", str(tmp)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return (True, "")
        error = (result.stderr or result.stdout).strip()
        return (False, error)

    except Exception as exc:
        return (False, str(exc))

    finally:
        if tmp and tmp.exists():
            tmp.unlink(missing_ok=True)


def apply_ruleset(ruleset: str) -> None:
    """Load a ruleset into the kernel with ``nft -f``.

    Writes *ruleset* to ``/tmp/_nft_apply.conf``, runs ``nft --file``, and
    removes the temporary file.  The live ruleset is replaced atomically by
    the ``flush ruleset`` directive that ``core.rules`` includes at the top of
    every generated string.

    Parameters
    ----------
    ruleset:
        The nftables ruleset string to apply.

    Raises
    ------
    RuntimeError
        If ``nft`` exits with a non-zero return code.  The error message
        includes nft's stderr output.
    """
    tmp: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", delete=False, prefix="nft_apply_"
        ) as fh:
            fh.write(ruleset)
            tmp = Path(fh.name)
        tmp.chmod(0o600)
        result = subprocess.run(
            ["nft", "--file", str(tmp)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"nft -f failed:\n{(result.stderr or result.stdout).strip()}"
            )
        print("[state] Ruleset applied atomically")
    finally:
        if tmp and tmp.exists():
            tmp.unlink(missing_ok=True)


def save_conf(ruleset: str, path: Path = NFT_CONF) -> None:
    """Persist a ruleset string to the nftables configuration file.

    This is intentionally separate from :func:`apply_ruleset` — writing the
    conf file makes the ruleset survive a reboot (via ``nftables.service``),
    but the caller decides whether and when to do that.

    Parameters
    ----------
    ruleset:
        The nftables ruleset string to persist.
    path:
        Destination path.  Defaults to ``/etc/nftables.conf``.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(ruleset)
    # 0o644 so the watchdog (running as fw-admin) can read this file directly
    # for marker validation before triggering an `nft -f` auto-repair. The conf
    # mirrors the live ruleset (visible via `sudo nft list ruleset`) and contains
    # no secrets, so world-read is acceptable.
    path.chmod(0o644)
    print(f"[state] Ruleset saved to {path}")


# ── Persistent dynamic sets ──────────────────────────────────────────────────

def _canonical_set_name(set_name: str) -> str:
    if set_name not in _KNOWN_SETS:
        raise ValueError(f"Unknown dynamic set: {set_name!r}")
    return set_name


def _audit_actor() -> str:
    """Return the best local identity available for a firewall mutation."""
    return (
        os.environ.get("SUDO_USER")
        or os.environ.get("USER")
        or os.environ.get("LOGNAME")
        or str(os.getuid())
    )


def _audit_set_mutation(
    action: str,
    set_name: str,
    ips: list[str],
    *,
    path: Path = _AUDIT_LOG_FILE,
    timeout: str | None = None,
) -> None:
    """Append a best-effort JSONL audit record for a dynamic set mutation."""
    record = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "actor": _audit_actor(),
        "uid": os.getuid(),
        "euid": os.geteuid(),
        "action": action,
        "timeout": timeout,
        "set": set_name,
        "items": list(ips),
        "count": len(ips),
    }
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a") as fh:
            fh.write(json.dumps(record, sort_keys=True) + "\n")
        path.chmod(0o640)
    except OSError as exc:
        print(f"[state] WARNING: audit log write failed: {exc}")


def load_persistent_sets(path: Path = _SETS_STATE_FILE) -> dict[str, list[str]]:
    """Load dynamic set members persisted across ruleset reloads."""
    from utils.validation import (
        validate_block_target,
        validate_ipv4_network,
        validate_trusted_target,
    )

    data: dict[str, list[str]] = {name: [] for name in _KNOWN_SETS}
    if not path.exists():
        return data
    try:
        raw = json.loads(path.read_text())
    except Exception:
        return data
    if not isinstance(raw, dict):
        return data
    for name in _KNOWN_SETS:
        values = raw.get(name, [])
        if isinstance(values, list):
            clean: set[str] = set()
            for value in values:
                raw_value = str(value).strip()
                if not raw_value:
                    continue
                if name == SET_BLOCKED:
                    result = validate_block_target(raw_value)
                elif name == SET_TRUSTED:
                    result = validate_trusted_target(raw_value)
                else:
                    result = validate_ipv4_network(raw_value)
                if result.ok:
                    clean.add(result.value)
                else:
                    print(
                        f"[state] WARNING: ignored unsafe persisted {name} member "
                        f"{raw_value!r}: {result.reason}"
                    )
            data[name] = sorted(clean)
    return data


def save_persistent_sets(sets: dict[str, list[str]], path: Path = _SETS_STATE_FILE) -> None:
    """Atomically persist dynamic set members."""
    path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        name: sorted({str(v).strip() for v in sets.get(name, []) if str(v).strip()})
        for name in _KNOWN_SETS
    }
    tmp = path.with_suffix(".tmp")
    with tmp.open("w") as fh:
        fh.write(json.dumps(data, indent=2) + "\n")
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, path)
    _relax_for_daemon_group(path)


_DAEMON_GROUP = "fw-admin"


def _relax_for_daemon_group(path: Path) -> None:
    """Make *path* group-readable by the daemon account.

    The dynamic-sets file is written both by fw-admin (interactive !block) and
    by root (sudo apply / geoblock reapply). A 0600 root-owned file would lock
    the fw-admin webui/report daemons out, so set group ownership to the daemon
    group and mode 0640. Best-effort: chown to a group we don't belong to fails
    for a non-root writer, which is fine — an fw-admin-written file is already
    readable by fw-admin.
    """
    try:
        import grp
        gid = grp.getgrnam(_DAEMON_GROUP).gr_gid
        os.chown(path, -1, gid)
        path.chmod(0o640)
    except (KeyError, PermissionError, OSError):
        try:
            path.chmod(0o600)
        except OSError:
            pass


def persist_set_member(set_name: str, ip: str, *, present: bool) -> None:
    """Record that *ip* is present or absent in a dynamic set."""
    set_name = _canonical_set_name(set_name)
    sets = load_persistent_sets()
    members = set(sets.get(set_name, []))
    if present:
        members.add(ip)
    else:
        members.discard(ip)
    sets[set_name] = sorted(members)
    save_persistent_sets(sets)


def merge_live_sets_into_persistent() -> dict[str, list[str]]:
    """Merge readable live nft set members into persistent state."""
    merged = load_persistent_sets()
    changed = False
    for set_name in _KNOWN_SETS:
        live = set_list(set_name, persistent_fallback=False)
        if live:
            union = sorted(set(merged.get(set_name, [])) | set(live))
            if union != merged.get(set_name, []):
                merged[set_name] = union
                changed = True
    if changed:
        save_persistent_sets(merged)
    return merged


# ── Backup & restore ──────────────────────────────────────────────────────────

def backup_ruleset(backup_dir: Path = _BACKUP_DIR) -> Path:
    """Snapshot the currently loaded ruleset to a timestamped file.

    Runs ``nft list ruleset`` and writes the output to
    ``<backup_dir>/nftables_YYYYMMDD_HHMMSS.conf``.  If no ruleset is loaded
    (empty output or command failure), writes a ``flush ruleset`` placeholder
    so that a subsequent :func:`restore_ruleset` call leaves the kernel in a
    clean state.

    Parameters
    ----------
    backup_dir:
        Directory to write the backup into.  Created if absent.
        Defaults to ``<project_root>/state/``.

    Returns
    -------
    Path
        Absolute path of the written backup file.
    """
    backup_dir.mkdir(parents=True, exist_ok=True)
    ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
    dest = backup_dir / f"nftables_{ts}.conf"

    result = subprocess.run(
        ["nft", "list", "ruleset"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        dest.write_text(result.stdout)
    else:
        dest.write_text("# empty\nflush ruleset\n")
        print("[state] WARNING: no existing ruleset — placeholder backup written")

    dest.chmod(0o600)
    print(f"[state] Backup: {dest}")
    return dest


def restore_ruleset(
    backup: Optional[Path] = None,
    backup_dir: Path = _BACKUP_DIR,
) -> None:
    """Restore a previously backed-up ruleset.

    Parameters
    ----------
    backup:
        Path to a specific backup file.  When ``None``, the most recent
        ``nftables_*.conf`` file in *backup_dir* is used.
    backup_dir:
        Directory to search for backups when *backup* is ``None``.
        Defaults to ``<project_root>/state/``.

    Raises
    ------
    RuntimeError
        If no backup file can be found, or if ``nft -f`` fails.
    """
    if backup is None:
        candidates = sorted(backup_dir.glob("nftables_*.conf"), reverse=True)
        if not candidates:
            raise RuntimeError(f"No backups found in {backup_dir}")
        backup = candidates[0]

    print(f"[state] Restoring {backup.name} ...")
    result = subprocess.run(
        ["nft", "--file", str(backup)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Restore failed: {(result.stderr or result.stdout).strip()}"
        )
    print(f"[state] Restored from {backup.name}")


# ── Dynamic set modifiers ─────────────────────────────────────────────────────

def set_add(set_name: str, ip: str, timeout: str | None = None) -> bool:
    """Add an IP address to a live nftables set without reloading the ruleset.

    *timeout* is an optional nftables duration (e.g. ``"48h"``) making the entry
    self-expire; the target set must carry the ``timeout`` flag.
    """
    return set_add_bulk(set_name, [ip], timeout=timeout) == 1


def set_add_bulk(set_name: str, ips: list[str], timeout: str | None = None) -> int:
    """Add multiple IP addresses to a live nftables set efficiently.

    Parameters
    ----------
    set_name:
        Name of the set in the ``ip firewall`` table.
    ips:
        List of IPv4 addresses or CIDR prefixes to add.

    Returns
    -------
    int
        Number of elements successfully added.
    """
    if not ips:
        return 0
    set_name = _canonical_set_name(set_name)

    # Use a temporary file to avoid shell argument length limits
    suffix = f" timeout {timeout}" if timeout else ""
    elements = ", ".join(f"{ip}{suffix}" for ip in ips)
    script = f"add element ip firewall {set_name} {{ {elements} }}\n"

    tmp: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as fh:
            fh.write(script)
            tmp = Path(fh.name)

        result = subprocess.run(["nft", "-f", str(tmp)], capture_output=True, text=True)
        if result.returncode != 0:
            print(f"[state] WARNING: bulk add to {set_name} failed: {result.stderr.strip()}")
            return 0

        # Persist only permanent entries. A timed grant lives solely in the
        # live set and expires on its own; persisting it would resurrect it
        # (without its timeout) on the next ruleset reload.
        if not timeout:
            sets = load_persistent_sets()
            members = set(sets.get(set_name, []))
            members.update(ips)
            sets[set_name] = sorted(members)
            save_persistent_sets(sets)
        _audit_set_mutation("add", set_name, ips, timeout=timeout)
        return len(ips)
    finally:
        if tmp and tmp.exists():
            tmp.unlink(missing_ok=True)


def set_del(set_name: str, ip: str) -> bool:
    """Remove an IP address from a live nftables set."""
    return set_del_bulk(set_name, [ip]) == 1


def set_del_bulk(set_name: str, ips: list[str]) -> int:
    """Remove multiple IP addresses from a live nftables set efficiently."""
    if not ips:
        return 0
    set_name = _canonical_set_name(set_name)

    elements = ", ".join(ips)
    script = f"delete element ip firewall {set_name} {{ {elements} }}\n"

    tmp: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".conf", delete=False) as fh:
            fh.write(script)
            tmp = Path(fh.name)

        result = subprocess.run(["nft", "-f", str(tmp)], capture_output=True, text=True)
        if result.returncode != 0:
            print(f"[state] WARNING: bulk delete from {set_name} failed: {result.stderr.strip()}")
            return 0

        sets = load_persistent_sets()
        members = set(sets.get(set_name, []))
        for ip in ips:
            members.discard(ip)
        sets[set_name] = sorted(members)
        save_persistent_sets(sets)
        _audit_set_mutation("delete", set_name, ips)
        return len(ips)
    finally:
        if tmp and tmp.exists():
            tmp.unlink(missing_ok=True)


def set_list(set_name: str, *, persistent_fallback: bool = True) -> List[str]:
    """Return the current members of a live nftables set.

    Parameters
    ----------
    set_name:
        Name of the set in the ``ip firewall`` table.

    Returns
    -------
    list[str]
        List of IP/CIDR strings currently in the set, or ``[]`` if the set is
        empty, the ruleset is not loaded, or the command fails.
    """
    set_name = _canonical_set_name(set_name)
    result = subprocess.run(
        ["nft", "list", "set", "ip", "firewall", set_name],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0 or not result.stdout:
        return load_persistent_sets().get(set_name, []) if persistent_fallback else []
    match = re.search(r"elements\s*=\s*\{([^}]*)\}", result.stdout)
    if not match:
        return load_persistent_sets().get(set_name, []) if persistent_fallback else []
    raw = match.group(1).strip()
    if not raw:
        return load_persistent_sets().get(set_name, []) if persistent_fallback else []
    return [x.strip() for x in raw.split(",") if x.strip()]


# ── Convenience wrappers ──────────────────────────────────────────────────────

def block_ip(ip: str, *, never_block: Optional[List[str]] = None) -> bool:
    """Add *ip* to the ``blocked_ips`` set (drop in INPUT and OUTPUT).

    Parameters
    ----------
    ip:
        IPv4 address or CIDR prefix to block.

    Returns
    -------
    bool
        ``True`` on success.
    """
    from utils.validation import validate_block_target
    result = validate_block_target(ip, never_block=never_block or [])
    if not result.ok:
        print(f"[state] WARNING: {result.reason}")
        return False
    return set_add(SET_BLOCKED, result.value)


def unblock_ip(ip: str) -> bool:
    """Remove *ip* from the ``blocked_ips`` set.

    Parameters
    ----------
    ip:
        IPv4 address or CIDR prefix to unblock.

    Returns
    -------
    bool
        ``True`` on success.
    """
    from utils.validation import validate_ipv4_network
    result = validate_ipv4_network(ip)
    if not result.ok:
        print(f"[state] WARNING: {result.reason}")
        return False
    return set_del(SET_BLOCKED, result.value)


def trusted_access_list() -> list[dict]:
    """Return trusted_ips members with expiry info for the ``!access`` command.

    Each entry is ``{"ip": str, "permanent": bool, "expires": str | None}``.
    ``expires`` is the human string nftables reports (milliseconds trimmed),
    e.g. ``"44m59s"``; ``None`` for permanent entries.
    """
    result = subprocess.run(
        ["nft", "list", "set", "ip", "firewall", SET_TRUSTED],
        capture_output=True, text=True,
    )
    if result.returncode != 0 or not result.stdout:
        return []
    match = re.search(r"elements\s*=\s*\{([^}]*)\}", result.stdout, re.DOTALL)
    if not match:
        return []
    entries: list[dict] = []
    for chunk in match.group(1).split(","):
        parts = chunk.split()
        if not parts:
            continue
        ip = parts[0]
        expires = None
        if "expires" in parts:
            raw = parts[parts.index("expires") + 1]
            expires = re.sub(r"(\d+)ms$", "", raw) or raw   # trim trailing ms
        entries.append({"ip": ip, "permanent": expires is None, "expires": expires})
    return sorted(entries, key=lambda e: (e["permanent"], e["ip"]))


def allow_ip(ip: str, timeout: str | None = None) -> bool:
    """Add *ip* to the ``trusted_ips`` set (SSH override from non-LAN addresses).

    Parameters
    ----------
    ip:
        IPv4 address or CIDR prefix to trust.

    Returns
    -------
    bool
        ``True`` on success.
    """
    from utils.validation import validate_trusted_target
    result = validate_trusted_target(ip)
    if not result.ok:
        print(f"[state] WARNING: {result.reason}")
        return False
    return set_add(SET_TRUSTED, result.value, timeout=timeout)


def disallow_ip(ip: str) -> bool:
    """Remove *ip* from the ``trusted_ips`` set.

    Parameters
    ----------
    ip:
        IPv4 address or CIDR prefix to remove from the trusted set.

    Returns
    -------
    bool
        ``True`` on success.
    """
    from utils.validation import validate_ipv4_network
    result = validate_ipv4_network(ip)
    if not result.ok:
        print(f"[state] WARNING: {result.reason}")
        return False
    return set_del(SET_TRUSTED, result.value)
